DATA:
  name: "MNIST"
  img_size: 28
  num_classes: 10
  img_channels: 1
MODEL:
  # backbone: "deep_conv_MNIST"
  backbone: "dynamic_deep_conv_MNIST"
  g_cond_mtd: "cBN"
  # g_info_injection: "concat"
  # d_cond_mtd: "W/O"
  d_cond_mtd: "AC"
  aux_cls_type: "W/O"
  g_conv_dim: "N/A"
  d_conv_dim: "N/A"
LOSS:
  adv_loss: "vanilla"
  cond_lambda: 1.0
OPTIMIZATION:
  batch_size: 64
  d_updates_per_step: 1
  total_steps: 100
PRE:
  apply_rflip: False
DYNAMIC:
  occupy_start: 0.5
  occupy_end: 1.0
  randomly_select: True
  keepd: -1