DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
MODEL:
  backbone: "deep_conv"
  g_cond_mtd: "cBN"
  d_cond_mtd: "PD"
  aux_cls_type: "W/O"
  g_conv_dim: "N/A"
  d_conv_dim: "N/A"
  # g_init: "ortho"
  apply_d_sn: False
LOSS:
  adv_loss: "vanilla"
OPTIMIZATION:
  batch_size: 64
  d_updates_per_step: 2
  total_steps: 200000
PRE:
  apply_rflip: False
DYNAMIC:
  occupy_start: -1.0
  occupy_end: -1.0
  randomly_select: False
  keepd: -1
